---
# Default gateway used for the management interface
mgmt_gateway: 172.16.1.1

# iBGP ASN for the fabric
bgp_as: 65001

# BGP distance for specific route types
bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200

# PE router group
pe:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.1.0/27
    virtual_router_mac_address: 00:1c:73:00:dc:00
    # ISIS NET system id prefix
    isis_system_id_prefix: '0000.0001'
    spanning_tree_mode: mstp
    overlay_address_families: 
      - evpn

  # If two nodes (and only two) are in the same node_group, they will automatically form an MLAG pair
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    - group: WAN1-PE1-2
      nodes:
        # Definition of hostnames under the node_group
        - name: pe1
          id: 1
          mgmt_ip: 172.16.1.101/24
        - name: pe2
          id: 2
          mgmt_ip: 172.16.1.102/24

    - group: WAN1-PE3
      nodes:
        - name: pe3
          id: 3
          mgmt_ip: 172.16.1.103/24

# As MPLS-VPN WAN networks are often not pure l3ls-topologies, but arbitrary mesh topologies/hub-and-spoke, etc, the l3ls-evpn method
# of defining underlay topology on the nodes/node-defaults with uplink_switches, uplink_interfaces and uplink_switch_interfaces is
# substituted for this free-standing data model of core_interfaces, where all p2p underlay links in the topology are defined.

core_interfaces:
  # First, an IP-pool for the underlay p2p links is defined
  p2p_links_ip_pools:
    - name: core_pool
      ipv4_pool: 100.64.48.0/24
  p2p_links_profiles:
    - name: core_profile
      # speed: 100gfull
      # On vEOS-lab, MTU values larger than 1500 can cause issues, in an actual production network this is normally a larger value
      mtu: 1500
      isis_metric: 50
      ip_pool: core_pool
      isis_circuit_type: level-2
      isis_authentication_mode: md5
      isis_authentication_key: $1c$sTNAlR6rKSw=
  p2p_links:
    # PE1 links
    - nodes: [ pe1, pe2 ]
      id: 1
      interfaces: [ Ethernet1, Ethernet1 ]
      profile: core_profile
    - nodes: [ pe1, pe3 ]
      id: 2
      interfaces: [ Ethernet2, Ethernet2 ]
      profile: core_profile
    # PE2 links
    - nodes: [ pe2, pe3 ]
      id: 3
      interfaces: [ Ethernet3, Ethernet3 ]
      profile: core_profile
